version: "3.8"

services:
  # ===========================================
  # 🗃️ BASE DE DATOS POSTGRES
  # ===========================================
  monitor-precios-srv:
    image: postgres:16
    container_name: monitor-precios-db
    restart: unless-stopped
    env_file:
      - ./bot/.env        
    volumes:
      - /volume1/docker/postgres-data/monitor-precios-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # ===========================================
  # 🧰 ADMINER (interfaz web de BD)
  # ===========================================
  adminer:
    image: adminer
    container_name: adminer-monitor-precios
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - monitor-precios-srv

  # ===========================================
  # ⚡ REDIS (message broker)
  # ===========================================
  redis:
    image: redis:7-alpine
    container_name: monitor-precios-redis
    restart: unless-stopped
    ports:
      - "6379:6379" # opcional, puedes quitarlo si no accedes desde fuera
    volumes:
      - /volume1/docker/redis-data/monitor-precios:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  # ===========================================
  # 🤖 BOT TELEGRAM (entrada de tickets)
  # ===========================================
  bot:
    build: ./bot
    container_name: monitor-precios-bot
    command: ["python", "-u", "bot.py"]
    restart: "no"
    env_file:
      - ./bot/.env    
    depends_on:
      - monitor-precios-srv
      - redis
    volumes:
      - ./bot:/app
      - ./bot/keys:/app/keys
      - ./bot/prompts:/app/prompts
      - ./bot/cache:/app/cache
    ports:
      - "8001:8000" # opcional, útil para debug

  # ===========================================
  # 🔍 WORKER OCR (usa Google Document AI)
  # ===========================================
  worker_ocr:
    build: ./bot
    container_name: monitor-precios-worker-ocr
    command: ["python", "-u", "worker_ocr.py"]
    restart: "no"
    env_file:
      - ./bot/.env    
    depends_on:
      - redis
      - monitor-precios-srv
    volumes:
      - ./bot:/app
      - ./bot/keys:/app/keys
      - ./bot/cache:/app/cache

  # ===========================================
  # 🧠 WORKER IA (usa Ollama + Llama3)
  # ===========================================
  worker_ia:
    build: ./bot
    container_name: monitor-precios-worker-ia
    command: ["python", "-u", "worker_ia.py"]
    restart: "no"
    env_file:
      - ./bot/.env    
    depends_on:
      - redis
      - monitor-precios-srv
    volumes:
      - ./bot:/app
      - ./bot/cache:/app/cache

  # ===========================================
  # 💾 WORKER BD (inserta tickets en PostgreSQL)
  # ===========================================
  worker_db:
    build: ./bot
    container_name: monitor-precios-worker-db
    command: ["python", "-u", "worker_db.py"]
    restart: "no"
    env_file:
      - ./bot/.env    
    depends_on:
      - redis
      - monitor-precios-srv
    volumes:
      - ./bot:/app
      - ./bot/cache:/app/cache
