# docker-compose.yml
version: "3.8"

services:
  monitor-precios-srv:
    image: postgres:16
    container_name: monitor-precios-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: adm1n
      POSTGRES_PASSWORD: Micro1101mania19
      POSTGRES_DB: monitorprecios
    volumes:
      - /volume1/docker/postgres-data/monitor-precios-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: adminer-monitor-precios
    restart: unless-stopped
    ports:
      - "8081:8080"

  # ================================
  # 🧰 ENTORNO DE DESARROLLO (edición en vivo)
  # ================================
  bot-dev:
    build: ./bot
    container_name: monitor-precios-bot-dev
    restart: unless-stopped
    env_file:
      - ./bot/.env
    environment:
      TZ: Europe/Madrid
    depends_on:
      - monitor-precios-srv
    volumes:
      - ./bot:/app               # 🔥 monta todo el código local
      - ./bot/keys:/app/keys     # credenciales Document AI
    ports:
      - "8001:8000"              # puerto opcional para debug

  # ================================
  # 🚀 ENTORNO DE PRODUCCIÓN (multi-stage optimizado)
  # ================================
  bot-prod:
    build: ./bot
    container_name: monitor-precios-bot-prod
    restart: unless-stopped
    env_file:
      - ./bot/.env
    environment:
      TZ: Europe/Madrid
    depends_on:
      - monitor-precios-srv
    volumes:
      - ./bot/cache:/app/cache   # logs y temporales
      - ./bot/keys:/app/keys     # credenciales Document AI

